name: CD - Docker Deploy

on:
  push:
    branches: [ desarrollo ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mini-secure-app .

      - name: Run container
        run: docker run -d -p 3001:3001 --name app mini-secure-app

      - name: Check running containers
        run: docker ps